spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:opensample}
    username: ${DB_USER:opensample}
    password: ${DB_PASSWORD:opensample}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  thymeleaf:
    cache: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: ${SERVER_PORT:8080}
